server:
  address: 127.0.0.1
  port: 9000

# =========================================================
# Application settings
# =========================================================
app-configuration:
  datasource-path:

---
spring:
  profiles: development
  application:
    name: medicine_analytics

server:
  address: 127.0.0.1
  port: 9000

---
spring:
  profiles: production
server:
  address: 127.0.0.1
  port: 9000